# Generated by Django 5.2.17 on 2026-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('prompt', models.TextField()),
                ('schema_sql', models.TextField(help_text="DDL + seed data, run inside this problem's own Postgres schema.")),
                ('solution_sql', models.TextField(help_text="Canonical SELECT — run live to check submissions and power 'reveal solution'.")),
                ('hint', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
